import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, it } from "node:test";

import { Config } from "../src/config.ts";
import type { Docker } from "../src/docker.ts";
import { DockerError, UsageError } from "../src/errors.ts";
import { loadProviders } from "../src/providers.ts";
import { release } from "../src/release.ts";
import {
  buildCompose, parsePs, resolveImage, serviceName, Stack, volumeName, writeCompose,
} from "../src/stack.ts";
import { FakeDocker, PINNED, useEnv } from "./helpers.ts";

const PROVIDERS = loadProviders();
const CLAUDE = PROVIDERS.get("claude")!;
const SECRETS = "/home/u/.config/modelmux/secrets.env";
useEnv(); // restores release.pinnedImage

describe("image", () => {
  it("precedence: --image, saved, pinned", () => {
    release.pinnedImage = () => PINNED;
    assert.equal(resolveImage(new Config()), PINNED);
    assert.equal(resolveImage(new Config(new Map(), "saved:1")), "saved:1");
    assert.equal(resolveImage(new Config(new Map(), "saved:1"), "flag:2"), "flag:2");
  });

  it("a dev build without an image", () => {
    release.pinnedImage = () => null;
    assert.throws(() => resolveImage(new Config()), (e: unknown) =>
      e instanceof UsageError && /no pinned server image/.test(e.message) && e.hint!.includes("--image"));
  });

  for (const bad of ["--privileged", "a b", "x;rm", "x".repeat(300), "-x"]) {
    it(`rejects ${bad.slice(0, 20)}`, () => {
      assert.throws(() => resolveImage(new Config(), bad), UsageError);
    });
  }
});

describe("compose", () => {
  it("is hardened and isolated", () => {
    const compose = buildCompose(PROVIDERS, new Config(new Map([["codex", 9102]])), "img:1", SECRETS) as any;
    assert.equal(compose.name, "modelmux");
    const claude = compose.services["modelmux-claude"];
    const codex = compose.services["modelmux-codex"];
    for (const service of [claude, codex]) {
      assert.equal(service.image, "img:1");
      assert.equal(service.read_only, true);
      assert.deepEqual(service.cap_drop, ["ALL"]);
      assert.deepEqual(service.security_opt, ["no-new-privileges:true"]);
      assert.equal(service.user, "10001:10001");
      assert.equal(service.restart, "on-failure:3");
      assert.deepEqual(service.tmpfs, ["/tmp:rw,noexec,nosuid,nodev,size=512m"]);
      assert.deepEqual(service.env_file, [SECRETS]);
      assert.ok(service.ports.every((p: string) => p.startsWith("127.0.0.1:")));
      // Only named volumes: never a host path, never the Docker socket.
      for (const mount of service.volumes as string[]) {
        assert.ok(!/^[/.~]/.test(mount.split(":")[0]!));
        assert.ok(!mount.includes("docker.sock"));
      }
      assert.ok(!("privileged" in service));
    }
    assert.deepEqual(claude.environment, { MODELMUX_DRIVER: "claude" });
    assert.deepEqual(claude.ports, ["127.0.0.1:8101:8000"]);
    assert.deepEqual(codex.ports, ["127.0.0.1:9102:8000"]);
    assert.deepEqual(claude.volumes, ["claude-home:/home/modelmux/driver-home"]);
    assert.deepEqual(claude.labels, { "io.modelmux.managed": "true", "io.modelmux.provider": "claude" });
    assert.deepEqual(compose.volumes, {
      "claude-home": { external: true, name: "modelmux_claude-home" },
      "codex-home": { external: true, name: "modelmux_codex-home" },
    });
    assert.ok(!JSON.stringify(compose).includes("MODELMUX_API_KEYS"));
  });

  it("writes the compose file only when it changes", () => {
    const dir = mkdtempSync(path.join(tmpdir(), "modelmux-compose-"));
    const compose = buildCompose(PROVIDERS, new Config(), "img:1", SECRETS);
    assert.equal(writeCompose(dir, compose), true);
    const text = readFileSync(path.join(dir, "compose.yaml"), "utf8");
    assert.ok(text.startsWith("# Generated by modelmux"));
    const body = JSON.parse(text.slice(text.indexOf("\n") + 1));
    assert.deepEqual(Object.keys(body.services).sort(), ["modelmux-claude", "modelmux-codex"]);
    // Same content again: nothing to apply, so running containers can stay.
    assert.equal(writeCompose(dir, compose), false);
    assert.equal(writeCompose(dir, buildCompose(PROVIDERS, new Config(), "img:2", SECRETS)), true);
  });

  it("names", () => {
    assert.equal(serviceName(CLAUDE), "modelmux-claude");
    assert.equal(volumeName(CLAUDE), "modelmux_claude-home");
  });
});

describe("ps parsing", () => {
  it("lines and arrays", () => {
    const lines =
      '{"Service": "modelmux-claude", "State": "running", "Health": "", "ExitCode": 0}\n' +
      '{"Service": "modelmux-codex", "State": "exited", "Health": "", "ExitCode": 3}\n';
    const states = parsePs(lines);
    assert.equal(states.get("modelmux-claude")!.state, "running");
    assert.equal(states.get("modelmux-codex")!.exitCode, 3);
    const array = parsePs("[" + lines.trim().replace("\n", ",") + "]");
    assert.deepEqual([...array.keys()], [...states.keys()]);
  });

  for (const output of ["", "not json", "[1, 2]", '{"State": "running"}']) {
    it(`garbage: ${JSON.stringify(output)}`, () => {
      assert.equal(parsePs(output).size, 0);
    });
  }
});

describe("stack operations", () => {
  const make = (): [Stack, FakeDocker] => {
    const docker = new FakeDocker();
    return [new Stack(docker as unknown as Docker, mkdtempSync(path.join(tmpdir(), "modelmux-stack-"))), docker];
  };

  it("helper containers are hardened", () => {
    const [stack] = make();
    const args = stack.helperArgs(CLAUDE, "img:1", ["claude", "auth", "status"]);
    assert.deepEqual(args.slice(0, 2), ["run", "--rm"]);
    for (const flag of ["--read-only", "--cap-drop", "--security-opt", "--user"]) assert.ok(args.includes(flag));
    assert.equal(args[args.indexOf("-v") + 1], "modelmux_claude-home:/home/modelmux/driver-home");
    assert.equal(args[args.indexOf("-e") + 1], "HOME=/home/modelmux/driver-home");
    assert.equal(args[args.indexOf("--entrypoint") + 1], "claude");
    assert.deepEqual(args.slice(-3), ["img:1", "auth", "status"]);
    assert.ok(!args.includes("-p")); // helpers never open ports
    assert.ok(!args.includes("--publish"));
  });

  it("logged in", async () => {
    const [stack, docker] = make();
    docker.when("volume", "inspect", { returns: [1, "", "no such volume"] });
    assert.equal(await stack.loggedIn(CLAUDE, "img:1"), false);
    assert.deepEqual(docker.called("run"), []); // no helper container without a volume
    docker.when("volume", "inspect", { returns: [0, "[]", ""] });
    docker.when("run", { returns: [0, "", ""] });
    assert.equal(await stack.loggedIn(CLAUDE, "img:1"), true);
    docker.when("run", { returns: [1, "", ""] });
    assert.equal(await stack.loggedIn(CLAUDE, "img:1"), false);
  });

  it("creates a volume once", async () => {
    const [stack, docker] = make();
    docker.when("volume", "inspect", { returns: [1, "", ""] });
    await stack.ensureVolume(CLAUDE);
    const creates = docker.called("volume", "create");
    assert.equal(creates.length, 1);
    assert.equal(creates[0]!.at(-1), "modelmux_claude-home");
    assert.ok(creates[0]!.includes("io.modelmux.provider=claude"));
    docker.when("volume", "inspect", { returns: [0, "", ""] });
    await stack.ensureVolume(CLAUDE);
    assert.equal(docker.called("volume", "create").length, 1);
  });

  it("pulls a missing image", async () => {
    const [stack, docker] = make();
    docker.when("image", "inspect", { returns: [0, "", ""] });
    assert.equal(await stack.ensureImage("ghcr.io/x/y:1"), false);
    docker.when("image", "inspect", { returns: [1, "", ""] });
    assert.equal(await stack.ensureImage("ghcr.io/x/y:1"), true);
    assert.ok(docker.called("pull", "ghcr.io/x/y:1").length);
  });

  it("a missing local image has a build hint", async () => {
    const [stack, docker] = make();
    docker.when("image", "inspect", { returns: [1, "", ""] }).when("pull", { returns: [1, "", ""] });
    await assert.rejects(stack.ensureImage("modelmux:dev"), (e: unknown) =>
      e instanceof DockerError && /not on this machine/.test(e.message) && e.hint!.includes("docker build"));
    await assert.rejects(stack.ensureImage("ghcr.io/x/y:1"), (e: unknown) =>
      e instanceof DockerError && /docker pull failed/.test(e.message));
  });

  it("no states without a compose file", async () => {
    const [stack, docker] = make();
    assert.equal((await stack.states()).size, 0);
    assert.deepEqual(docker.calls, []);
  });
});
