from __future__ import annotations

import json
from pathlib import Path

import pytest

from modelmux_cli import _pinned
from modelmux_cli.config import Config
from modelmux_cli.errors import DockerError, UsageError
from modelmux_cli.providers import load_providers
from modelmux_cli.stack import (
    Stack,
    build_compose,
    parse_ps,
    resolve_image,
    service_name,
    volume_name,
    write_compose,
)
from tests.conftest import FakeDocker

PROVIDERS = load_providers()
CLAUDE = PROVIDERS["claude"]
SECRETS = Path("/home/u/.config/modelmux/secrets.env")


# ------------------------------------------------------------------ image


def test_resolve_image_precedence(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(_pinned, "IMAGE", "ghcr.io/smit153/modelmux@sha256:" + "a" * 64)
    assert resolve_image(Config()).endswith("a" * 64)
    assert resolve_image(Config(image="saved:1")) == "saved:1"
    assert resolve_image(Config(image="saved:1"), "flag:2") == "flag:2"


def test_dev_build_without_image(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(_pinned, "IMAGE", None)
    with pytest.raises(UsageError, match="no pinned server image") as info:
        resolve_image(Config())
    assert "--image" in (info.value.hint or "")


@pytest.mark.parametrize("bad", ["--privileged", "a b", "x;rm", "", "-x"])
def test_invalid_image_reference(bad: str) -> None:
    with pytest.raises(UsageError):
        resolve_image(Config(), bad or "x" * 300)


# ------------------------------------------------------------------ compose


def test_compose_is_hardened_and_isolated() -> None:
    compose = build_compose(PROVIDERS, Config(ports={"codex": 9102}), "img:1", SECRETS)
    assert compose["name"] == "modelmux"
    claude = compose["services"]["modelmux-claude"]
    codex = compose["services"]["modelmux-codex"]
    for service in (claude, codex):
        assert service["image"] == "img:1"
        assert service["read_only"] is True
        assert service["cap_drop"] == ["ALL"]
        assert service["security_opt"] == ["no-new-privileges:true"]
        assert service["user"] == "10001:10001"
        assert service["restart"] == "on-failure:3"
        assert service["tmpfs"] == ["/tmp:rw,noexec,nosuid,nodev,size=512m"]
        assert service["env_file"] == [str(SECRETS)]
        assert all(p.startswith("127.0.0.1:") for p in service["ports"])
        # Only named volumes: never a host path, never the Docker socket.
        for mount in service["volumes"]:
            source = mount.split(":", 1)[0]
            assert not source.startswith(("/", ".", "~"))
            assert "docker.sock" not in mount
        assert "privileged" not in service
    assert claude["environment"] == {"MODELMUX_DRIVER": "claude"}
    assert claude["ports"] == ["127.0.0.1:8101:8000"]
    assert codex["ports"] == ["127.0.0.1:9102:8000"]
    assert claude["volumes"] == ["claude-home:/home/modelmux/driver-home"]
    assert claude["labels"] == {"io.modelmux.managed": "true", "io.modelmux.provider": "claude"}
    assert compose["volumes"] == {
        "claude-home": {"external": True, "name": "modelmux_claude-home"},
        "codex-home": {"external": True, "name": "modelmux_codex-home"},
    }
    assert "MODELMUX_API_KEYS" not in json.dumps(compose)


def test_write_compose(tmp_path: Path) -> None:
    path = write_compose(tmp_path, build_compose(PROVIDERS, Config(), "img:1", SECRETS))
    text = path.read_text()
    assert text.startswith("# Generated by modelmux")
    body = json.loads(text.split("\n", 1)[1])
    assert set(body["services"]) == {"modelmux-claude", "modelmux-codex"}


def test_names() -> None:
    assert service_name(CLAUDE) == "modelmux-claude"
    assert volume_name(CLAUDE) == "modelmux_claude-home"


# ------------------------------------------------------------------ ps parsing


def test_parse_ps_lines_and_array() -> None:
    lines = (
        '{"Service": "modelmux-claude", "State": "running", "Health": "", "ExitCode": 0}\n'
        '{"Service": "modelmux-codex", "State": "exited", "Health": "", "ExitCode": 3}\n'
    )
    states = parse_ps(lines)
    assert states["modelmux-claude"].state == "running"
    assert states["modelmux-codex"].exit_code == 3
    assert parse_ps("[" + lines.strip().replace("\n", ",") + "]").keys() == states.keys()


@pytest.mark.parametrize("output", ["", "not json", "[1, 2]", '{"State": "running"}'])
def test_parse_ps_garbage(output: str) -> None:
    assert parse_ps(output) == {}


# ------------------------------------------------------------------ stack operations


@pytest.fixture
def stack(tmp_path: Path) -> tuple[Stack, FakeDocker]:
    docker = FakeDocker()
    return Stack(docker, tmp_path), docker  # type: ignore[arg-type]


def test_helper_container_is_hardened(stack: tuple[Stack, FakeDocker]) -> None:
    s, _ = stack
    args = s.helper_args(CLAUDE, "img:1", ("claude", "auth", "status"))
    assert args[:2] == ["run", "--rm"]
    for flag in ("--read-only", "--cap-drop", "--security-opt", "--user"):
        assert flag in args
    assert args[args.index("-v") + 1] == "modelmux_claude-home:/home/modelmux/driver-home"
    assert args[args.index("-e") + 1] == "HOME=/home/modelmux/driver-home"
    assert args[args.index("--entrypoint") + 1] == "claude"
    assert args[-3:] == ["img:1", "auth", "status"]
    assert "-p" not in args  # helpers never open ports
    assert "--publish" not in args


def test_logged_in(stack: tuple[Stack, FakeDocker]) -> None:
    s, docker = stack
    docker.when("volume", "inspect", returns=(1, "", "no such volume"))
    assert s.logged_in(CLAUDE, "img:1") is False
    assert not docker.called("run")  # no helper container when there is no volume
    docker.when("volume", "inspect", returns=(0, "[]", ""))
    docker.when("run", returns=(0, "", ""))
    assert s.logged_in(CLAUDE, "img:1") is True
    docker.when("run", returns=(1, "", ""))
    assert s.logged_in(CLAUDE, "img:1") is False


def test_ensure_volume_idempotent(stack: tuple[Stack, FakeDocker]) -> None:
    s, docker = stack
    docker.when("volume", "inspect", returns=(1, "", ""))
    s.ensure_volume(CLAUDE)
    (create,) = docker.called("volume", "create")
    assert create[-1] == "modelmux_claude-home"
    assert "io.modelmux.provider=claude" in create
    docker.when("volume", "inspect", returns=(0, "", ""))
    s.ensure_volume(CLAUDE)
    assert len(docker.called("volume", "create")) == 1


def test_ensure_image(stack: tuple[Stack, FakeDocker]) -> None:
    s, docker = stack
    docker.when("image", "inspect", returns=(0, "", ""))
    assert s.ensure_image("ghcr.io/x/y:1") is False
    docker.when("image", "inspect", returns=(1, "", ""))
    assert s.ensure_image("ghcr.io/x/y:1") is True
    assert docker.called("pull", "ghcr.io/x/y:1")


def test_local_image_missing_has_build_hint(stack: tuple[Stack, FakeDocker]) -> None:
    s, docker = stack
    docker.when("image", "inspect", returns=(1, "", "")).when("pull", returns=(1, "", ""))
    with pytest.raises(DockerError, match="not on this machine") as info:
        s.ensure_image("modelmux:dev")
    assert "docker build" in (info.value.hint or "")
    with pytest.raises(DockerError, match="docker pull failed"):
        s.ensure_image("ghcr.io/x/y:1")


def test_states_without_compose_file(stack: tuple[Stack, FakeDocker]) -> None:
    s, docker = stack
    assert s.states() == {}
    assert docker.calls == []
