"""The ModelMux containers on this machine: image, compose file, login volumes.

All containers belong to the compose project ``modelmux``. Each provider has
one service (``modelmux-<provider>``) and one *external* login volume
(``modelmux_<provider>-home``) that only ``modelmux logout`` deletes.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from modelmux_cli import release
from modelmux_cli.config import Config
from modelmux_cli.docker import PULL_TIMEOUT, Docker
from modelmux_cli.errors import CliError, DockerError, UsageError
from modelmux_cli.files import write_private
from modelmux_cli.providers import Provider, shared_dir

PROJECT = "modelmux"
COMPOSE_FILE = "compose.yaml"  # JSON content; YAML is a superset of JSON
CONTAINER_PORT = 8000
# tmpfs mount spec inside helper containers (not a host path)
CONTAINER_TMP = "/tmp:rw,noexec,nosuid,nodev,size=64m"  # noqa: S108
_IMAGE_REF = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/:@-]{0,254}$")


def volume_name(provider: Provider) -> str:
    return f"{PROJECT}_{provider.volume}"


def service_name(provider: Provider) -> str:
    return f"{PROJECT}-{provider.name}"


def resolve_image(config: Config, override: str | None = None) -> str:
    """The image to run: --image, then the saved override, then the pinned release image."""
    image = override or config.image or release.pinned_image()
    if image is None:
        raise UsageError(
            "This development build of modelmux has no pinned server image.",
            hint="Pass one explicitly, e.g. --image modelmux:dev (it is remembered).",
        )
    if not _IMAGE_REF.fullmatch(image):
        raise UsageError(f"{image!r} is not a valid image reference.")
    return image


def service_template() -> dict[str, Any]:
    path = shared_dir() / "templates" / "compose-service.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise CliError("The compose template is invalid.", hint="Please report this bug.")
    return data


def build_compose(
    providers: dict[str, Provider], config: Config, image: str, secrets_file: Path
) -> dict[str, Any]:
    template = service_template()
    services: dict[str, Any] = {}
    volumes: dict[str, Any] = {}
    for name, provider in sorted(providers.items()):
        services[service_name(provider)] = {
            **template,
            "image": image,
            "environment": {"MODELMUX_DRIVER": provider.driver},
            "env_file": [str(secrets_file)],
            "volumes": [f"{provider.volume}:{provider.home}"],
            "ports": [f"127.0.0.1:{config.port(name)}:{CONTAINER_PORT}"],
            "networks": [PROJECT],
            "labels": {**template.get("labels", {}), "io.modelmux.provider": name},
        }
        volumes[provider.volume] = {"external": True, "name": volume_name(provider)}
    return {
        "name": PROJECT,
        "services": services,
        "volumes": volumes,
        "networks": {PROJECT: {"driver": "bridge"}},
    }


def write_compose(directory: Path, compose: dict[str, Any]) -> Path:
    path = directory / COMPOSE_FILE
    header = "# Generated by modelmux. Do not edit: changes are overwritten by 'modelmux up'.\n"
    write_private(path, header + json.dumps(compose, indent=2) + "\n")
    return path


@dataclass(frozen=True)
class ServiceState:
    service: str
    state: str  # running, exited, restarting, created, ...
    health: str  # healthy, unhealthy, starting, or ""
    exit_code: int | None


class Stack:
    def __init__(self, docker: Docker, home: Path) -> None:
        self.docker = docker
        self.home = home

    @property
    def compose_file(self) -> Path:
        return self.home / COMPOSE_FILE

    # ------------------------------------------------------------ image

    def image_present(self, image: str) -> bool:
        return self.docker.run("image", "inspect", image, check=False).ok

    def ensure_image(self, image: str) -> bool:
        """Pull ``image`` if it is not present. Returns True if it was pulled."""
        if self.image_present(image):
            return False
        try:
            self.docker.run("pull", image, timeout=PULL_TIMEOUT)
        except DockerError as exc:
            if "/" in image.split("@", maxsplit=1)[0]:
                raise
            # A local-only name such as modelmux:dev.
            raise DockerError(
                f"The image {image} is not on this machine and could not be downloaded.",
                hint=f"Build it first: docker build -f docker/Dockerfile -t {image} .",
            ) from exc
        return True

    # ------------------------------------------------------------ volumes

    def volume_exists(self, provider: Provider) -> bool:
        return self.docker.run("volume", "inspect", volume_name(provider), check=False).ok

    def ensure_volume(self, provider: Provider) -> None:
        if not self.volume_exists(provider):
            self.docker.run(
                "volume", "create",
                "--label", "io.modelmux.managed=true",
                "--label", f"io.modelmux.provider={provider.name}",
                volume_name(provider),
            )  # fmt: skip

    # ------------------------------------------------------------ helper containers

    def helper_args(
        self,
        provider: Provider,
        image: str,
        command: tuple[str, ...],
        extra: tuple[str, ...] = (),
    ) -> list[str]:
        """``docker run`` arguments for a short-lived, hardened helper container.

        ``extra`` adds run options such as ``-it`` or ``--name``.
        """
        return [
            "run", "--rm", *extra,
            "--read-only", "--tmpfs", CONTAINER_TMP,
            "--cap-drop", "ALL", "--security-opt", "no-new-privileges:true",
            "--user", "10001:10001",
            "--label", "io.modelmux.managed=true",
            "-v", f"{volume_name(provider)}:{provider.home}",
            "-e", f"HOME={provider.home}",
            "--entrypoint", command[0],
            image, *command[1:],
        ]  # fmt: skip

    def logged_in(self, provider: Provider, image: str) -> bool:
        if not self.volume_exists(provider):
            return False
        result = self.docker.run(
            *self.helper_args(provider, image, provider.status_command), check=False, timeout=90
        )
        return result.returncode == provider.logged_in_exit_code

    # ------------------------------------------------------------ compose

    def compose(self, *args: str, **kwargs: Any) -> Any:
        return self.docker.compose(PROJECT, self.compose_file, *args, **kwargs)

    def states(self) -> dict[str, ServiceState]:
        """Current containers of the project, by service name. Empty if none."""
        if not self.compose_file.exists():
            return {}
        result = self.compose("ps", "--all", "--format", "json", check=False)
        if not result.ok:
            return {}
        return parse_ps(result.stdout)


def parse_ps(output: str) -> dict[str, ServiceState]:
    """``docker compose ps --format json`` output: one object per line, or one array."""
    text = output.strip()
    if not text:
        return {}
    try:
        items = (
            json.loads(text)
            if text.startswith("[")
            else [json.loads(line) for line in text.splitlines() if line.strip()]
        )
    except ValueError:
        return {}
    states: dict[str, ServiceState] = {}
    for item in items:
        if not isinstance(item, dict) or not isinstance(item.get("Service"), str):
            continue
        code = item.get("ExitCode")
        states[item["Service"]] = ServiceState(
            service=item["Service"],
            state=str(item.get("State", "")),
            health=str(item.get("Health", "")),
            exit_code=code if isinstance(code, int) else None,
        )
    return states
