/**
 * The ModelMux containers on this machine: image, compose file, login volumes.
 *
 * All containers belong to the compose project `modelmux`. Each provider has
 * one service (`modelmux-<provider>`) and one *external* login volume
 * (`modelmux_<provider>-home`) that only `modelmux logout` deletes.
 */

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

import { type Config, pyJson } from "./config.ts";
import { type Docker, PULL_TIMEOUT, type Result, type RunOptions } from "./docker.ts";
import { CliError, DockerError, UsageError } from "./errors.ts";
import { writePrivate } from "./files.ts";
import { type Provider, sharedDir } from "./providers.ts";
import { pinnedImage } from "./release.ts";
import { repr, sortedStrings } from "./text.ts";

export const PROJECT = "modelmux";
export const COMPOSE_FILE = "compose.yaml"; // JSON content; YAML is a superset of JSON
export const CONTAINER_PORT = 8000;
// tmpfs mount spec inside helper containers (not a host path)
export const CONTAINER_TMP = "/tmp:rw,noexec,nosuid,nodev,size=64m";
const IMAGE_REF = /^[A-Za-z0-9][A-Za-z0-9._/:@-]{0,254}$/;

export function volumeName(provider: Provider): string {
  return `${PROJECT}_${provider.volume}`;
}

export function serviceName(provider: Provider): string {
  return `${PROJECT}-${provider.name}`;
}

/** The image to run: --image, then the saved override, then the pinned release image. */
export function resolveImage(config: Config, override: string | null = null): string {
  const image = override || config.image || pinnedImage();
  if (!image) {
    throw new UsageError("This development build of modelmux has no pinned server image.", {
      hint: "Pass one explicitly, e.g. --image modelmux:dev (it is remembered).",
    });
  }
  if (!IMAGE_REF.test(image)) throw new UsageError(`${repr(image)} is not a valid image reference.`);
  return image;
}

export function serviceTemplate(): Record<string, unknown> {
  const file = path.join(sharedDir(), "templates", "compose-service.json");
  const data: unknown = JSON.parse(readFileSync(file, "utf8"));
  if (typeof data !== "object" || data === null || Array.isArray(data)) {
    throw new CliError("The compose template is invalid.", { hint: "Please report this bug." });
  }
  return data as Record<string, unknown>;
}

export function buildCompose(
  providers: ReadonlyMap<string, Provider>,
  config: Config,
  image: string,
  secretsFile: string,
): Record<string, unknown> {
  const template = serviceTemplate();
  const labels = (template.labels ?? {}) as Record<string, unknown>;
  const services: Record<string, unknown> = {};
  const volumes: Record<string, unknown> = {};
  for (const name of sortedStrings(providers.keys())) {
    const provider = providers.get(name)!;
    services[serviceName(provider)] = {
      ...template,
      image,
      environment: { MODELMUX_DRIVER: provider.driver },
      env_file: [secretsFile],
      volumes: [`${provider.volume}:${provider.home}`],
      ports: [`127.0.0.1:${config.port(name)}:${CONTAINER_PORT}`],
      networks: [PROJECT],
      labels: { ...labels, "io.modelmux.provider": name },
    };
    volumes[provider.volume] = { external: true, name: volumeName(provider) };
  }
  return {
    name: PROJECT,
    services,
    volumes,
    networks: { [PROJECT]: { driver: "bridge" } },
  };
}

/** Write the compose file. Returns true if its content changed. */
export function writeCompose(directory: string, compose: Record<string, unknown>): boolean {
  const file = path.join(directory, COMPOSE_FILE);
  const header = "# Generated by modelmux. Do not edit: changes are overwritten by 'modelmux up'.\n";
  const content = header + pyJson(compose) + "\n";
  try {
    if (readFileSync(file, "utf8") === content) return false;
  } catch {
    // missing or unreadable: write it
  }
  writePrivate(file, content);
  return true;
}

export interface ServiceState {
  readonly service: string;
  readonly state: string; // running, exited, restarting, created, ...
  readonly health: string; // healthy, unhealthy, starting, or ""
  readonly exitCode: number | null;
}

export class Stack {
  readonly docker: Docker;
  readonly home: string;

  constructor(docker: Docker, home: string) {
    this.docker = docker;
    this.home = home;
  }

  get composeFile(): string {
    return path.join(this.home, COMPOSE_FILE);
  }

  // ------------------------------------------------------------ image

  async imagePresent(image: string): Promise<boolean> {
    return (await this.docker.run(["image", "inspect", image], { check: false })).ok;
  }

  /** Pull `image` if it is not present. Returns true if it was pulled. */
  async ensureImage(image: string): Promise<boolean> {
    if (await this.imagePresent(image)) return false;
    try {
      await this.docker.run(["pull", image], { timeout: PULL_TIMEOUT });
    } catch (error) {
      if (!(error instanceof DockerError) || image.split("@", 1)[0]!.includes("/")) throw error;
      // A local-only name such as modelmux:dev.
      throw new DockerError(
        `The image ${image} is not on this machine and could not be downloaded.`,
        { hint: `Build it first: docker build -f docker/Dockerfile -t ${image} .` },
      );
    }
    return true;
  }

  // ------------------------------------------------------------ volumes

  async volumeExists(provider: Provider): Promise<boolean> {
    return (await this.docker.run(["volume", "inspect", volumeName(provider)], { check: false })).ok;
  }

  async ensureVolume(provider: Provider): Promise<void> {
    if (!(await this.volumeExists(provider))) {
      await this.docker.run([
        "volume", "create",
        "--label", "io.modelmux.managed=true",
        "--label", `io.modelmux.provider=${provider.name}`,
        volumeName(provider),
      ]);
    }
  }

  // ------------------------------------------------------------ helper containers

  /**
   * `docker run` arguments for a short-lived, hardened helper container.
   *
   * `extra` adds run options such as `-it` or `--name`.
   */
  helperArgs(
    provider: Provider,
    image: string,
    command: readonly string[],
    extra: readonly string[] = [],
  ): string[] {
    return [
      "run", "--rm", ...extra,
      "--read-only", "--tmpfs", CONTAINER_TMP,
      "--cap-drop", "ALL", "--security-opt", "no-new-privileges:true",
      "--user", "10001:10001",
      "--label", "io.modelmux.managed=true",
      "-v", `${volumeName(provider)}:${provider.home}`,
      "-e", `HOME=${provider.home}`,
      "--entrypoint", command[0]!,
      image, ...command.slice(1),
    ];
  }

  async loggedIn(provider: Provider, image: string): Promise<boolean> {
    if (!(await this.volumeExists(provider))) return false;
    const result = await this.docker.run(this.helperArgs(provider, image, provider.statusCommand), {
      check: false,
      timeout: 90,
    });
    return result.returncode === provider.loggedInExitCode;
  }

  // ------------------------------------------------------------ compose

  compose(args: readonly string[], options: RunOptions = {}): Promise<Result> {
    return this.docker.compose(PROJECT, this.composeFile, args, options);
  }

  /** Current containers of the project, by service name. Empty if none. */
  async states(): Promise<Map<string, ServiceState>> {
    if (!existsSync(this.composeFile)) return new Map();
    const result = await this.compose(["ps", "--all", "--format", "json"], { check: false });
    if (!result.ok) return new Map();
    return parsePs(result.stdout);
  }
}

/** `docker compose ps --format json` output: one object per line, or one array. */
export function parsePs(output: string): Map<string, ServiceState> {
  const text = output.trim();
  const states = new Map<string, ServiceState>();
  if (!text) return states;
  let items: unknown[];
  try {
    items = text.startsWith("[")
      ? (JSON.parse(text) as unknown[])
      : text
          .split(/\r\n|\r|\n/)
          .filter((line) => line.trim())
          .map((line) => JSON.parse(line) as unknown);
  } catch {
    return states;
  }
  if (!Array.isArray(items)) return states;
  for (const item of items) {
    if (typeof item !== "object" || item === null || Array.isArray(item)) continue;
    const record = item as Record<string, unknown>;
    if (typeof record.Service !== "string") continue;
    const code = record.ExitCode;
    states.set(record.Service, {
      service: record.Service,
      state: pyStr(record.State ?? ""),
      health: pyStr(record.Health ?? ""),
      exitCode: Number.isInteger(code) ? (code as number) : null,
    });
  }
  return states;
}

/** Python's `str()` for the JSON scalars Docker reports. */
function pyStr(value: unknown): string {
  if (value === null) return "None";
  if (value === true) return "True";
  if (value === false) return "False";
  return typeof value === "string" ? value : JSON.stringify(value);
}
